### ISSUE TITLE
cudnn not found cuda9/cudnn 7.03

### ISSUE THREAD

**Issue by David-Levinthal** [fabiencro/knmt#62]
ubuntu 16.04 Nvidia V100
knmt version 
/usr/local/lib/python2.7/dist-packages/cupy-4.0.0b2-py2.7-linux-x86_64.egg/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
package version: 0.10.0
installed in: /home/levinth/knmt/nmt_chainer/utilities

*********** chainer version ***********
version 4.0.0b2
cuda True
cudnn True
cuda_version 9000
cudnn_version unavailable

but
levinth@zt-gpu-lin-1:~/knmt$ echo $CUDA_PATH
/usr/local/cuda
levinth@zt-gpu-lin-1:~/knmt$ echo $LD_LIBRARY_PATH
/opt/lib:/usr/local/cuda-9.0/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nccl:/usr/local/lib:/usr/local/mpi/lib:/usr/lib/nx/X11/Xinerama:/usr/lib/nx/X11:/home/levinth/torch/install/lib:/home/levinth/torch/install/lib:
levinth@zt-gpu-lin-1:~/knmt$ ls -l /usr/local/cuda
lrwxrwxrwx 1 root root 8 Nov  8 14:33 /usr/local/cuda -> cuda-9.0
levinth@zt-gpu-lin-1:~/knmt$ ls -l /usr/local/cuda/lib64/libcudnn*
lrwxrwxrwx 1 root root 43 Nov  8 15:21 /usr/local/cuda/lib64/libcudnn.so.7 -> /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3
lrwxrwxrwx 1 root root 43 Nov  8 15:14 /usr/local/cuda/lib64/libcudnn.so.7.0 -> /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3
levinth@zt-gpu-lin-1:~/knmt$ ls -l /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3
-rw-r--r-- 1 root root 285372592 Sep 15 20:02 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.3

does this have anything to do with https://github.com/chainer/chainer/issues/3922
where is ws_size?

**Comment by David-Levinthal** [comment]
Original invocation of knmt:
knmt train /data_nvme0/knmt_exp/exp1/knmt_data /data_nvme0/knmt_exp/exp1/knmt_train --gpu 0 --optimizer adam --weight_decay 1e-6 --use_goto --l2_gradient_clipping 1 --mb_size 128 --max_src_tgt_length 50 --Ei 1024 --Eo 1024 --Hi 1024 --Ho 1024 --Ha 1024 --Hl 1024 > knmt_1024_v100.log 2>&1
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/levinth/knmt/nmt_chainer/__main__.py", line 110, in <module>
    main()
  File "/home/levinth/knmt/nmt_chainer/__main__.py", line 100, in main
    func(args)
  File "nmt_chainer/training_module/train_config.py", line 290, in do_train
    import nmt_chainer.training_module.train
  File "nmt_chainer/training_module/train.py", line 35, in <module>
    import nmt_chainer.models.encoder_decoder
  File "nmt_chainer/models/encoder_decoder.py", line 16, in <module>
    import rnn_cells
  File "nmt_chainer/models/rnn_cells.py", line 24, in <module>
    import nmt_chainer.utilities.faster_gru as faster_gru
  File "nmt_chainer/utilities/faster_gru.py", line 16, in <module>
    libcudnn = cudnn.cudnn
AttributeError: 'module' object has no attribute 'cudnn'

[knmt_1024_v100.log](https://github.com/fabiencro/knmt/files/1627410/knmt_1024_v100.log)

attaching python setup.py -vvvv install logs for cupy and chainer
[chainer_setup.log](https://github.com/fabiencro/knmt/files/1627334/chainer_setup.log)
[setup_log.log](https://github.com/fabiencro/knmt/files/1627335/setup_log.log)
